/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnEnglishRouteImport } from './routes/learn-english'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnEnglishIndexRouteImport } from './routes/learn-english/index'
import { Route as LearnEnglishTopicSlugStepNumberRouteImport } from './routes/learn-english/$topicSlug.$stepNumber'

const LearnEnglishRoute = LearnEnglishRouteImport.update({
  id: '/learn-english',
  path: '/learn-english',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnEnglishIndexRoute = LearnEnglishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnEnglishRoute,
} as any)
const LearnEnglishTopicSlugStepNumberRoute =
  LearnEnglishTopicSlugStepNumberRouteImport.update({
    id: '/$topicSlug/$stepNumber',
    path: '/$topicSlug/$stepNumber',
    getParentRoute: () => LearnEnglishRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn-english': typeof LearnEnglishRouteWithChildren
  '/learn-english/': typeof LearnEnglishIndexRoute
  '/learn-english/$topicSlug/$stepNumber': typeof LearnEnglishTopicSlugStepNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn-english': typeof LearnEnglishIndexRoute
  '/learn-english/$topicSlug/$stepNumber': typeof LearnEnglishTopicSlugStepNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn-english': typeof LearnEnglishRouteWithChildren
  '/learn-english/': typeof LearnEnglishIndexRoute
  '/learn-english/$topicSlug/$stepNumber': typeof LearnEnglishTopicSlugStepNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn-english'
    | '/learn-english/'
    | '/learn-english/$topicSlug/$stepNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn-english' | '/learn-english/$topicSlug/$stepNumber'
  id:
    | '__root__'
    | '/'
    | '/learn-english'
    | '/learn-english/'
    | '/learn-english/$topicSlug/$stepNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnEnglishRoute: typeof LearnEnglishRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learn-english': {
      id: '/learn-english'
      path: '/learn-english'
      fullPath: '/learn-english'
      preLoaderRoute: typeof LearnEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-english/': {
      id: '/learn-english/'
      path: '/'
      fullPath: '/learn-english/'
      preLoaderRoute: typeof LearnEnglishIndexRouteImport
      parentRoute: typeof LearnEnglishRoute
    }
    '/learn-english/$topicSlug/$stepNumber': {
      id: '/learn-english/$topicSlug/$stepNumber'
      path: '/$topicSlug/$stepNumber'
      fullPath: '/learn-english/$topicSlug/$stepNumber'
      preLoaderRoute: typeof LearnEnglishTopicSlugStepNumberRouteImport
      parentRoute: typeof LearnEnglishRoute
    }
  }
}

interface LearnEnglishRouteChildren {
  LearnEnglishIndexRoute: typeof LearnEnglishIndexRoute
  LearnEnglishTopicSlugStepNumberRoute: typeof LearnEnglishTopicSlugStepNumberRoute
}

const LearnEnglishRouteChildren: LearnEnglishRouteChildren = {
  LearnEnglishIndexRoute: LearnEnglishIndexRoute,
  LearnEnglishTopicSlugStepNumberRoute: LearnEnglishTopicSlugStepNumberRoute,
}

const LearnEnglishRouteWithChildren = LearnEnglishRoute._addFileChildren(
  LearnEnglishRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnEnglishRoute: LearnEnglishRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
